imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@HorusFrontBundle/Resources/config/config.yml' }


framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        hinclude_default_template: HorusFrontBundle::hinclude.html.twig
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    translator:      { fallback: fr }
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       { path: /_fragment }
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false
    form:
      resources:
          - 'HorusFrontBundle:Main:forms.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Assetic Configuration
assetic:
    bundles:
        - AdminCoreBundle
        - HorusAdminBundle
        - HorusFrontBundle
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
        yui_css:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        closure:
          jar: "%kernel.root_dir%/Resources/java/compiler.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: false

controller_extra:
    factory:
        default_method: create
        default_static: false

elcodi_menu:
    route_provider:
        adapter: symfony

doctrine_cache:
    providers:
        elcodi:
            type: array

knp_gaufrette:
    adapters:
        local:
            local:
                directory: %kernel.root_dir%/../web/images
                create: true
    filesystems:
        local:
            adapter:    local

free_payment:
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id



#Services
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }



#Fos User Bundle
fos_user:
   db_driver:     orm
   firewall_name: main
   user_class:    Horus\AdminBundle\Entity\User

# Doctrine Extensions
stof_doctrine_extensions:
  orm:
    default:
      sluggable: true
      timestampable: true
      tree: true
      softdeleteable: true
      sortable: true