imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Assetic Configuration
assetic:
    bundles:
        - AdminCoreBundle
        - StoreCoreBundle
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: false

controller_extra:
    factory:
        default_method: create
        default_static: false

elcodi_menu:
    route_provider:
        adapter: symfony

doctrine_cache:
    providers:
        elcodi:
            type: array

knp_gaufrette:
    adapters:
        local:
            local:
                directory: %kernel.cache_dir%/tmp/gaufrette
                create: true
    filesystems:
        local:
            adapter:    local

free_payment:
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id
