security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username_email

    firewalls:
        dev:
          pattern:  ^/(_(profiler|wdt)|css|images|js)/
          security: false
        administration:
          pattern:        ^/administration
          form_login:
            provider:               fos_userbundle
            csrf_provider:          form.csrf_provider
            check_path:             /administration/login_check
            login_path:        /login
          logout:
            path:   /administration/logout
            target: /login
          remember_me:
              key:      "%secret%"
              lifetime: 31536000 # 365 jours en secondes
              path:     /
              domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER
        login:
          pattern:  ^/login$
          security: false
          remember_me:
            key: "%secret%"
            lifetime: 31536000 # 365 days in seconds
            path: /
            domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration, role: ROLE_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }