horus_admin_dashboard:
    path:     /
    defaults: { _controller: HorusAdminBundle:Main:dashboard }

horus_admin_login:
    path:     /login
    defaults: { _controller: HorusAdminBundle:Security:login }
